### ISSUE TITLE
Weeks does not start with Sunday in Turkish

### ISSUE THREAD

**Issue by sabriunal** [diegopvlk/Dosage#40]
In Turkish and some other countries, the first day of the week is Monday (meaning Pazartesi).

GNOME Calendar uses the correct format for this.

![Image](https://github.com/diegopvlk/Dosage/assets/6218679/acc4147e-243c-421e-9f47-12a60e305cbb)

On the other hand, Dosage starts the week from Monday.

![Week](https://github.com/diegopvlk/Dosage/assets/6218679/1c14f0da-8930-4163-88f1-a924d9d957aa)

You may check the following article for more information: https://www.timeanddate.com/calendar/days/

**Comment by sabriunal** [comment]
Thanks. Fixed.

**Comment by sabriunal** [comment]
Seems broken now. 
![Ekran Görüntüsü - 2024-01-29 23-01-17](https://github.com/diegopvlk/Dosage/assets/6218679/386a5ff8-e7fe-436d-aafc-d6f50afe2b2d)

**Comment by sabriunal** [comment]
I see two examples that seems the same or similar. 

https://gitlab.gnome.org/GNOME/gnome-calendar/-/blob/main/src/utils/gcal-utils.c?ref_type=heads#L330-387

https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/src/shell-util.c?ref_type=heads#L79-135

**Comment by sabriunal** [comment]
From Evolution

![Ekran Görüntüsü - 2024-01-30 00-24-37](https://github.com/diegopvlk/Dosage/assets/6218679/0ca90350-523b-4a00-a662-db36d005cbcb)

**Comment by sabriunal** [comment]
Could you use different date. E.g: 1, October 2017. Turkish timezone and daylight saving changed around 2016.

**Comment by erklyn** [comment]
I could try to tackle this.

**Comment by erklyn** [comment]
@diegopvlk looks fine and works fine on my system as well, returns 39 for me I am an in Turkey so works correctly.
